name: Create change
description: Create standard change in ServiceNow
inputs:
  commits_context:
    description: Commits context
    required: true
outputs:
  change-number:
    description: Change number
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: List commits
      id: commit-list
      run: |
        pwd
        ls -l
        ls -l ..
        ls -l $GITHUB_ACTION_PATH
        $GITHUB_ACTION_PATH/snow_change_helper.py list-commits
      shell: bash
      env:
        COMMITS_CONTEXT: ${{ inputs.commits_context }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Print
      shell: bash
      run: |
        echo ${{steps.commit-list.outputs.COMMITS_HTML}}
