name: Create change
description: Create standard change in ServiceNow
inputs:
  commits_context:
    description: Commits context
    required: true
outputs:
  change-number:
    description: Change number
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: List commits
      id: commit-list
      run: |
        pwd
        ls -l
        ls -l ..
        ls -l $GITHUB_ACTION_PATH
        $GITHUB_ACTION_PATH/snow_change_helper.py --output-mode stdout list-commits
      shell: bash
      env:
        COMMITS_CONTEXT: ${{ inputs.commits_context }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Set Greeting
    #   run: echo "Hello $INPUT_WHO_TO_GREET."
    #   shell: bash
    #   env:
    #     INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    # - name: Random Number Generator
    #   id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
