name: Create change
description: Create standard change in ServiceNow
inputs:
  github_token:
    description: Github token
    required: true
  short-description:
    description: Standard change customised short description
    required: true
  standard-change:
    description: Standard change template id
    required: true
  version:
    description: Release version (git tag)
    required: true
outputs:
  change-number:
    description: Change number
    value: ${{ steps.create-change.outputs.change-number }}
  change-sys-id:
    description: Change sys-id
    value: ${{ steps.create-change.outputs.sys-id }}
  change-link:
    description: Change link
    value: ${{ steps.create-change.outputs.change-link }}
runs:
  using: "composite"
  steps:
    - name: List commits
      id: commit-list
      run: |
        $GITHUB_ACTION_PATH/snow_change_helper.py list-commits
      shell: bash
      env:
        COMMITS_CONTEXT: ${{ toJSON(github.event.commits) }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Extract PR and Jira info
      if: github.event_name == 'push'
      id: extract-pr-jira
      shell: bash
      run: $GITHUB_ACTION_PATH/snow_change_helper.py extract-pr-jira
      env:
        HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_HTML_URL: ${{ github.event.repository.html_url }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Build change HTML
      id: build-change-html
      shell: bash
      run: $GITHUB_ACTION_PATH/snow_change_helper.py build-change-html
      env:
        RELEASE_VERSION: ${{ inputs.version }}
        PR_NUMBER: ${{ steps.extract-pr-jira.outputs.pull_request_number }}
        PR_LINK: ${{ steps.extract-pr-jira.outputs.pull_request_link }}
        JIRA_REFERENCE: ${{ steps.extract-pr-jira.outputs.jira_reference }}
        JIRA_LINK: ${{ steps.extract-pr-jira.outputs.jira_link }}
        COMMITS_HTML: ${{ steps.commit-list.outputs.COMMITS_HTML }}
        WORKFLOW_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Create and schedule change
      id: create-change
      shell: bash -euo pipefail {0}
      run: |
        $GITHUB_ACTION_PATH/snow_change_helper.py snow-command create \
          --short-description "$SHORT_DESCRIPTION" \
          --standard-change "$SNOW_STANDARD_CHANGE" | tee create_output.env

        source create_output.env

        $GITHUB_ACTION_PATH/snow_change_helper.py snow-command --verbose post-work-note \
          --number "$CHANGE_NUMBER" \
          --text "[code]$CHANGE_HTML[/code]"

        echo "Change created successfully and scheduled immediately"

        {
          echo "change-sys-id=$CHANGE_SYS_ID"
          echo "change-number=$CHANGE_NUMBER"
          echo "change-link=$CHANGE_LINK"
        } >> "$GITHUB_OUTPUT"
      env:
        SHORT_DESCRIPTION: ${{ inputs.short-description }}
        CHANGE_HTML: ${{ steps.build-change-html.outputs.CHANGE_HTML }}
